name: Metrics
on:
  # Update setiap jam 00:00
  schedule: [{cron: "0 0 * * *"}]
  # Bisa dijalankan manual
  workflow_dispatch:
  # Update setiap kali ada push ke branch master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          # Opsi konfigurasi
          user: azizpambayun
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Jakarta
